### ISSUE TITLE
PostHog Team Appreciation

### ISSUE THREAD

**Issue by yakkomajuri** [Yardanico/posthog-nim#1]
Hey @Yardanico! I'm a developer at PostHog and just came across this library. I've briefly dabbled with Nim and quite like the language. 

I'd like to send over some merch to you on behalf of PostHog. Could you send me an email at yakko[(at)]posthog[(.)]com so we can coordinate this?

**Comment by Yardanico** [comment]
Thanks for the heads up, I've sent you an email :)

**Comment by yakkomajuri** [comment]
Sent over a code! 

Happy to be supportive of the Nim community (even if indirectly).
